### PR TITLE
Added Current Location Feature

### PR DESCRIPTION
**Pull request by RishabhSri17**
This pull request addresses issue [#25](https://github.com/adaharshsingh/Propacity/issues/25) ,I had added feature of current location by adding one component LocationCard.jsx and adding few lines of code in /Context/index.jsx and app.jsx .

Change I have made-
- Added a LocationCard component that, when clicked, fetches the user's current latitude and longitude using the Geolocation API.
- Applied consistent styling to the LocationCard to match the existing CityCard layout.
- Integrated the fetched coordinates into the existing weather API to display the weather forecast for the user's current location.

Screenshot -
After First Commit - displaying Latitude and Longitude
Screenshot 2024-10-07 021544 (2)
After Second Commit - displaying Placename instead
Screenshot 2024-10-07 021711

Testing:
- Tested the feature locally by fetching the location multiple times and verifying the response.

Please accept my pull request and review the changes and let me know if any adjustments are needed. Thank you!

### CODE REVIEW

**Comment by RishabhSri17** [comment]
I had added also added feature of displaying Placename instead of Latitude/Longitude ,
for that we have to update our .env file by adding email-id (to fetch Placename) -
ex_email = your_email_id 

Screenshot 2024-10-07 024857

**Comment by adaharshsingh** [comment]
Hey !! Your current location feature work perfectly ; but its not showing the current city name in my setup ;but it seems to work in your setup ; can you tell me what the problem might be;
i have added VITE_EX_EMAIL as a env variable just as you suggested but it doesn't work;
Screenshot 2024-10-07 135928

**Comment by RishabhSri17** [comment]
Did you push my second commit regarding the place name update? I had updated LocationCard.jsx, and that might be why it's not reflecting. As far as I can see, you updated index.js by changing ex_email to VITE_EX_EMAIL and also added it in the .env file, so it should be working properly.

image

**Comment by adaharshsingh** [comment]
Its working now , Thanks for your contribution!

**Pull request merged**
